[build-system]
requires = ["setuptools>=58.3.0", "wheel>=0.37.0"]
build-backend = "setuptools.build_meta"

# Project metadata
[project]
name = "arclet-alconna"
version = "1.0.0"
description = "A High-performance, Generality, Humane Command Line Arguments Parser Library."
readme = "README.md"
requires_python = ">=3.8"
license = "MIT"
keywords = [
    "command",
    "argparse",
    "fast",
    "alconna",
    "cli",
    "command-line",
    "parsing",
    "optparse"
]

[tool.pylint.BASIC]
class-const-naming-style = "any"

[tool.pylint."MESSAGE CONTROL"]
max-line-length = 120
disable = [
    "broad-except",
    "wrong-import-order",
    "unused-import",
    "invalid-name",
    "use-a-generator",
    "unbalanced-tuple-unpacking",
    "inconsistent-return-statements",
    "redefined-builtin",
    "redefined-outer-name",
    "import-outside-toplevel",
    "too-many-arguments",
    "too-many-instance-attributes",
    "too-many-branches",
    "too-many-boolean-expressions",
    "too-many-locals",
    "too-many-statements",
    "too-many-return-statements",
    "super-init-not-called",
    "no-self-use"
]


[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # standard pragma
    "pragma: no cover",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "if (typing\\.)?TYPE_CHECKING( is True)?:",
    "\\.\\.\\.",
    "pass",
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    # Don't complain overload method / functions
    "@(typing\\.)?overload"
]